### ISSUE TITLE
Gradle project sync failed

### ISSUE THREAD

**Issue by javauser1234** [uDevel/widgetlab#2]
While adding this to my project, it throws:
Error:(46, 13) Failed to resolve: com.github.uDevel:widgetlab:0.9.2

I have done exactly as mentioned in the readme.

**Comment by uDevel** [comment]
Hello,

You have done this, right?
Make sure it's in your project level build.gradle, not your app level.

```xml 
Add to your project level build.gradle's allprojects

allprojects {
  repositories {
    ...
    maven { url 'https://jitpack.io' }
  }
}
```

Can you please double check that?  I will double check mine later today.

**Comment by javauser1234** [comment]
Yes, that's correct. I have added the jitpack to project level.

**Comment by uDevel** [comment]
Ok, I will check it later today.
You can use 0.9.1 for now.

Thanks

**Comment by uDevel** [comment]
It seems jitpack had some issues.
Can you try 0.9.2 again now?  I just tried it, and it works now.

**Comment by javauser1234** [comment]
Thanks for the update. I'll check it and let you know.

**Comment by uDevel** [comment]
Let me know if you still have the same issue.

**Comment by javauser1234** [comment]
Awesome. Now it works! I apologize for my late response. Was tied up with work.
Thanks again for great work.
