### ISSUE TITLE
Animation order always random

### ISSUE THREAD

**Issue by 365SplendidSuns** [uDevel/widgetlab#6]
Great widget, but I'm finding that setting the animationOrder attribute doesn't appear to do anything. Whatever it is set to the animation is always random.

**Comment by uDevel** [comment]
Can you give me an example code?  Let me test it out.  

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by 365SplendidSuns** [comment]
Sure. I just have the xml in my layout.

<com.udevel.widgetlab.TypingIndicatorView
        android:id="@+id/typingIndicator"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:visibility="gone"
        android:animateLayoutChanges="true"
        android:padding="10dp"
        app:dotSize="20dp"
        app:dotMaxCompressRatio="50%"
        app:animationOrder="sequence"
        app:showBackground="false"
        app:backgroundType="rounded"
        android:layout_above="@+id/im_input_bar"/>

**Comment by yombunker** [comment]
@365SplendidSuns stupid error, i forgot to add the break points in the switch :(

the fix is in PR #7

**Comment by 365SplendidSuns** [comment]
Not the first time it's happened and it won't be the last! Thanks for the fix and for the widget itself.

**Comment by yombunker** [comment]
Version 0.9.6 is out
