### ISSUE TITLE
Crash when Inflating

### ISSUE THREAD

**Issue by 365SplendidSuns** [uDevel/widgetlab#8]
My app is crashing with the error below. I'm not quite sure what is causing it to be honest as whenever I use it myself it works fine but our crash reports are showing this and some of our users are complaining about crashes.

It's working fine most of the time but this crash is happening enough for it to definitely be a problem.

Thank you for any help.

android.view.InflateException: Binary XML file line #25: Error inflating class com.udevel.widgetlab.TypingIndicatorView : at android.view.LayoutInflater.createView(LayoutInflater.java:620)
Caused by: java.lang.NullPointerException at com.udevel.widgetlab.TypingIndicatorView.stopDotAnimation(TypingIndicatorView.java:192)

**Comment by uDevel** [comment]
Let me investigate.
Thanks for reporting.

**Comment by 365SplendidSuns** [comment]
Thanks

**Comment by 365SplendidSuns** [comment]
Did you get anywhere with this? I totally appreciate your good work on this widget and am grateful to be able to use it but it's causing a lot of crashes so I need to know if I should remove it from my app or wait for a fix.

**Comment by yombunker** [comment]
@365SplendidSuns  do you have more pieces of the stacktrace that you can share? so that we know if it already was pause, stopped or destroyed the activity? cause is not crashing in our code, is crashing in Android's code, cause our handler can't be null and the argument passed shouldn't matter if is null or not. So is something inside the Handlers state that is making it crash.

**Comment by 365SplendidSuns** [comment]
@yombunker Thanks for the reply. I'm afraid I've never actually had it crash on me - I'm just getting these crash reports via Acra so I  don't have any more than I posted above. It is happening fairly frequently though. We are getting reports from users of the app crashing when they open the Activity though if that helps.

**Comment by yombunker** [comment]
@365SplendidSuns Thanks, let us look into it, and see if there is something we can do about it.

**Comment by uDevel** [comment]
At worst case, we just catch the crash and eat it.  Because that piece of code should never crash by the current logic.

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by uDevel** [comment]
Can you try the latest one now?
Still haven't figure out why would it crash at all, but we just catch the exception for now.

**Comment by 365SplendidSuns** [comment]
I've just released an updated version of my app. I'll get back to you later when I can see if the crash reports have dried up. Thanks for your help.
